name: Setup tools
description: 'Setup tools for repo workflows'

inputs:
  install-nodejs:
    description: "Install nodejs and setup repo's npm package"
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    # This Action bundles other reusable actions in case needed.

    # Install Node.js and its dependencies
    - name: Setup node.js and install dependencies
      if: inputs.install-nodejs == 'true'
      uses: ./.github/actions/nodejs-ci
      with:
        node-version: '18' # Version is hardcoded across all other steps to ensure stability of the code, although the `package.json` has `>=18` engine version
