# This workflow publishes snapshot releases as an npm package. These releases aren't supposed to be reusable in `production` environments.
# It's triggered manually in case a snapshot release would be needed for testing purposes.
name: Release Snapshot

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release-snapshot:
    name: Release Snapshot
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          install-nodejs: 'true'

      - name: Build and Publish a Snapshot to NPM
        run: |
          npm run release-snapshot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
