name: Slither Static Analysis

on:
  - pull_request

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
