name: Upload Docs

on:
  push:
    branches:
      - main
      - ci/evm-docs-to-github-pages

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  upload-docs:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - name: Run Upload Docs Action
        uses: axelarnetwork/axelar-gmp-sdk-solidity/.github/actions/upload-docs@ci/evm-docs-to-github-pages
        with:
          branches: main,ci/evm-docs-to-github-pages
          environment_name: github-pages
